spring:
  application:
    name: SpringBatchJms

  datasource:
    url: jdbc:h2:tcp://localhost:9092/D:/db/test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    show-sql: true
    generate-ddl: true
    properties:
      hibernate.format_sql: true

  batch:
    jdbc:
      initialize-schema: always
